# Generated by Django 3.1.7 on 2021-04-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0002_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='Description',
        ),
    ]
