# Generated by Django 3.1.7 on 2021-04-03 04:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0003_remove_games_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ladders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='media/Games')),
                ('console', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('season', models.IntegerField(default=0)),
                ('teams', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('rules', ckeditor.fields.RichTextField()),
                ('playoff_info', ckeditor.fields.RichTextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tlou.games')),
            ],
        ),
    ]
