# Generated by Django 3.1.7 on 2021-04-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0004_ladders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladders',
            name='image',
            field=models.ImageField(upload_to='media/Ladders'),
        ),
    ]
