# Generated by Django 3.1.7 on 2021-04-10 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tlou', '0005_auto_20210403_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpass', models.CharField(default='', max_length=50)),
                ('add1', models.CharField(default='', max_length=500)),
                ('add2', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zipcode', models.IntegerField(default=0)),
                ('tpass', models.CharField(default='', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
