# Generated by Django 3.1.7 on 2021-04-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0008_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='Name',
            new_name='Heading',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
    ]
