# Generated by Django 3.1.7 on 2021-04-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0011_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=400)),
                ('SubHeading', models.CharField(max_length=400, null=True)),
                ('link', models.CharField(default='#', max_length=400)),
                ('image', models.ImageField(null=True, upload_to='media/Sliders')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
