# Generated by Django 3.1.7 on 2021-04-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0012_sliders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(default='#', max_length=400)),
                ('icon', models.ImageField(upload_to='media/Icon')),
            ],
        ),
    ]
