# Generated by Django 3.1.7 on 2021-04-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0013_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='icon',
        ),
        migrations.AddField(
            model_name='social',
            name='faicon',
            field=models.CharField(default='fa-facebook', max_length=100),
        ),
    ]
