# Generated by Django 3.1.7 on 2021-04-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0014_auto_20210413_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(null=True, upload_to='media/Sliders')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
