# Generated by Django 3.1.7 on 2021-04-15 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tlou', '0015_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/Teams')),
                ('Win', models.IntegerField()),
                ('Lose', models.IntegerField()),
                ('Trophies', models.IntegerField()),
                ('Name', models.CharField(max_length=1000)),
                ('Member1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member1', to=settings.AUTH_USER_MODEL)),
                ('Member10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member10', to=settings.AUTH_USER_MODEL)),
                ('Member11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member11', to=settings.AUTH_USER_MODEL)),
                ('Member12', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member12', to=settings.AUTH_USER_MODEL)),
                ('Member13', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member13', to=settings.AUTH_USER_MODEL)),
                ('Member14', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member14', to=settings.AUTH_USER_MODEL)),
                ('Member15', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member15', to=settings.AUTH_USER_MODEL)),
                ('Member2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member2', to=settings.AUTH_USER_MODEL)),
                ('Member3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member3', to=settings.AUTH_USER_MODEL)),
                ('Member4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member4', to=settings.AUTH_USER_MODEL)),
                ('Member5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member5', to=settings.AUTH_USER_MODEL)),
                ('Member6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member6', to=settings.AUTH_USER_MODEL)),
                ('Member7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member7', to=settings.AUTH_USER_MODEL)),
                ('Member8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member8', to=settings.AUTH_USER_MODEL)),
                ('Member9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member9', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
