# Generated by Django 3.1.7 on 2021-04-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0017_auto_20210416_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladders',
            name='maxmembers',
            field=models.IntegerField(default=2),
        ),
    ]
