# Generated by Django 3.1.7 on 2021-04-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0018_auto_20210416_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladders',
            name='minmembers',
        ),
        migrations.AlterField(
            model_name='ladders',
            name='maxmembers',
            field=models.CharField(default='11', max_length=20),
        ),
    ]
