# Generated by Django 3.1.7 on 2021-04-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0019_auto_20210416_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ladder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tlou.ladders'),
        ),
    ]
