# Generated by Django 3.1.7 on 2021-04-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0020_team_ladder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
