# Generated by Django 3.1.7 on 2021-04-16 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tlou', '0021_auto_20210416_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='Member1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Member1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='Trophies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='Win',
            field=models.IntegerField(default=0),
        ),
    ]
