# Generated by Django 3.1.7 on 2021-05-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0024_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='ContactMessage1',
        ),
    ]
