# Generated by Django 3.1.7 on 2021-05-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0025_auto_20210510_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage1',
            new_name='ContactMessage',
        ),
    ]
